---
- name: Create systemd unit for {{ app_name }}
  template:
    src:  app_service.j2
    dest: /etc/systemd/system/{{ app_name }}.service
  notify: Reload systemd

- name: Start {{ app_name }} service
  systemd:
    name: "{{ app_name }}"
    state: started
    enabled: yes