---
- name: Clone {{ app_name }} repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ app_path }}/{{ app_name }}"
    version: "{{ repo_version }}"
    update: yes
    force: yes
  become_user: "{{ app_user }}"

- name: Generate .env
  copy:
    remote_src: true
    src: "{{ app_path }}/{{ app_name }}/.env.example"
    dest: "{{ app_path }}/{{ app_name }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    force: no
  become_user: "{{ app_user }}"

- name: Install {{ app_name }} dependencies
  npm:
    path: "{{ app_path }}/{{ app_name }}"
  become_user: "{{ app_user }}"